### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by psvenk** [KB1RD/LearnASM#21]
I don't see a license for LearnASM. Does this mean that you intend it to be "source-available" proprietary software (see but don't touch), or have you just not yet gotten around to adding a license? The former is [implied due to U.S. copyright law](https://choosealicense.com/no-permission/), so it would be nice if you added a license so that people can contribute code to this project and borrow code from this project (assuming that you intend for this to be free/libre and open-source software).

**Comment by KB1RD** [comment]
Sorry about that... I'm in the process of moving stuff around and should've attached the license file originally. (I think I forgot to re-add it when I re-wrote the application?) I've just updated it, it was supposed to be GPL v3.0.

Feel free to use the code, but it's a bit questionable (to say the least!) and I have a few known issues with the simulator.

**Comment by KB1RD** [comment]
@psvenk If you find anything else missing or incorrect, do not hesitate to contact me and I'll update it ASAP.
